name: SonarCloud Scan

on:
  push:
    branches:
      - main   #  Trigger only on pushes to main

env:
  SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}   #  SonarCloud URL
  SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
  SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      # 1 Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2️ Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3️ Run SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: ./app
          args: >
            -Dsonar.organization=${{ env.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
            -Dsonar.host.url=${{ env.SONAR_HOST_URL }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   #  Secret token for authentication
