name: Terraform Deploy (via Terraform Cloud)

# Trigger this workflow after Docker build + Trivy scan completes
on:
  workflow_run:
    workflows: ["Docker Build and Trivy Scan"]  # Only run after this workflow
    types:
      - completed

env:
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}    #  Terraform Cloud API token (secure)
  TERRAFORM_FOLDER: ./Terraform                #  Folder containing my Terraform configs (main.tf, etc.)
  
jobs:
  terraform-cloud-run:
    runs-on: ubuntu-latest

    steps:
      # 1️ Checkout repo (needed to access Terraform folder in GitHub Actions)
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2️ Set up Terraform CLI in the GitHub runner
      - name: Set up Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.7.5'             # Optional: match Terraform Cloud workspace version
        # This only installs Terraform on the runner for triggering TFC runs; 
        # it does NOT run apply locally. All state management stays in Terraform Cloud.

      # Additional: Info step for hiring managers to see / debugging
      - name: Info
        run: |
          echo "Terraform Cloud run triggered for folder: ${{ env.TERRAFORM_FOLDER }}"
          echo "All state, env variables, and deployments are managed in Terraform Cloud."
